@CommonScenarios_HostAddress = https://localhost:8001
@firstOption = true

GET {{CommonScenarios_HostAddress}}/my-options/

###
POST {{CommonScenarios_HostAddress}}/notify/some-cool@email.com

###
GET {{CommonScenarios_HostAddress}}/options/true

###
GET {{CommonScenarios_HostAddress}}/options/false

###
GET {{CommonScenarios_HostAddress}}/factory/true

###
GET {{CommonScenarios_HostAddress}}/factory/false

###
GET {{CommonScenarios_HostAddress}}/monitor/true

###
GET {{CommonScenarios_HostAddress}}/monitor/false

###
GET {{CommonScenarios_HostAddress}}/snapshot/true

###
GET {{CommonScenarios_HostAddress}}/snapshot/false

###
