@Facade_HostAddress = https://localhost:9004

GET {{Facade_HostAddress}}/opaque/CheckOrderStatus
###

POST {{Facade_HostAddress}}/opaque/PlaceOrder
Content-Type: application/json

{
    "productId": "123", 
    "quantity": 5
}

###

GET {{Facade_HostAddress}}/transparent/CheckOrderStatus/123

###

POST {{Facade_HostAddress}}/transparent/PlaceOrder
Content-Type: application/json

{
    "productId": "123", 
    "quantity": 5
}

###
