@Web_HostAddress = https://localhost:57362
@ProductId = 3
@NonExistingProductId = 4

GET {{Web_HostAddress}}/products

###

GET {{Web_HostAddress}}/products/{{ProductId}}

###


GET {{Web_HostAddress}}/products/{{NonExistingProductId}}

###
