using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.EntityFrameworkCore;
using System.Reflection;
using Web.Features;

var builder = WebApplication.CreateBuilder(args);
builder.AddExceptionMapper(builder =>
{
    builder.Map<DbUpdateException>().ToStatusCode(StatusCodes.Status409Conflict);
    builder.Map<DbUpdateConcurrencyException>().ToStatusCode(StatusCodes.Status409Conflict);
});
builder.AddFluentValidationEndpointFilter();
builder.Services
    .AddFluentValidationAutoValidation()
    .AddValidatorsFromAssembly(Assembly.GetExecutingAssembly())
;
builder.Services.AddFeatures();

var app = builder.Build();
app.UseExceptionMapper();
app.MapFeatures();

await app.SeedFeaturesAsync();

app.Run();

// Workaround that makes the autogenerated program public so tests can
// access it without granting internal visibility.
#pragma warning disable CA1050 // Declare types in namespaces
public partial class Program { }
#pragma warning restore CA1050 // Declare types in namespaces